---
- hosts: localhost
  become: yes
  vars:
    ansible_localhost_root_pass_file: "{{ (local_credentials_path, 'localhost_root_pass') | path_join }}"
    ansible_become_pass: "{{ lookup('file', ansible_localhost_root_pass_file) }}"
  roles:
  - name: korbad.alma_workstation.packages
  - name: korbad.alma_workstation.chrome
  - name: korbad.alma_workstation.snapd
  - name: korbad.alma_workstation.discord
  - name: korbad.alma_workstation.vscode
  - name: korbad.alma_workstation.1password
  - name: korbad.alma_workstation.gh_cli
