---
- hosts: localhost
  become: yes
  roles:
  - name: korbad.alma_workstation.packages
    vars:
      package_list:
      - python3-pip
      - nmap
  - name: korbad.alma_workstation.chrome
  - name: korbad.alma_workstation.snapd
  - name: korbad.alma_workstation.discord
  - name: korbad.alma_workstation.vscode
  - name: korbad.alma_workstation.1password
  - name: korbad.alma_workstation.gh_cli
