---
- hosts: localhost
  become: yes
  vars_prompt:
  - name: ansible_become_pass
    prompt: become password?
    private: yes
  roles:
  - name: korbad.alma_workstation.packages
    vars:
      package_list:
      - elfutils-libelf-devel
  - name: korbad.alma_workstation.virtual_box
  - name: korbad.alma_workstation.packages
    vars:
      package_list:
      - make
      - gcc
      - perl
      - kernel-devel
  - name: korbad.alma_workstation.vagrant
