---
- hosts: localhost
  roles:
  - name: korbad.alma_workstation.github_repos
    vars:
      managed_github_orgs:
        - github_org: Korbad
      managed_github_repos:
        - git_link: git@github.com:Korbad/gcp.git
          github_org: Korbad
          github_repo_name: gcp
