---
- hosts: localhost
  become: yes
  vars_prompt:
  - name: ansible_become_pass
    prompt: become password?
    private: yes
  roles:
  - name: korbad.bootstrap.manage_ansible_user_and_ssh_access
 
